apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: zodiaczodiacpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zodiaczodiacpipelinesjavascriptdocker 
    spec:
      containers:
        - name: zodiaczodiacpipelinesjavascriptdocker 
          image: eusdsolacr001.azurecr.io/zodiaczodiacpipelinesjavascriptdocker
          ports:
          - containerPort: 8080